apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamza-app
  namespace: hamza-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hamza-app
  template:
    metadata:
      labels:
        app: hamza-app
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: hamza-app
          image: 192.168.1.7:3443/test/test-app:v1
          ports:
            - containerPort: 80
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: hamza-config
                  key: PORT
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hamza-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hamza-secret
                  key: MONGO_PASSWORD
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
